### ISSUE TITLE
Thumbnail Service

### ISSUE THREAD

**Issue by rileytwo** [sbarex/QLExt#2]
In the readme, you say "For now this extension don't provide a thumbnail service for the icon. I don't think a preview of the contents in the icon is a necessary feature for the source files. I rather think it would be more useful to have a distinctive file type icon.". However, I'm able to preview the file in the icon--did you not intend for this, or am I missing the point you're making here?

![screenshot](https://user-images.githubusercontent.com/34988536/67336102-64ab8e00-f4ea-11e9-8792-0e77c4afb772.png)

**Comment by Nef10** [comment]
I think the content of the right panel is actual a preview. The thumbnail is the small icon on the right side next to the file name.

**Comment by rileytwo** [comment]
Ah, that makes sense. Thanks @Nef10!

**Comment by sbarex** [comment]
Yes, my extension don't provide the finder icon thumbnail. To generate the icon you need a different system extension. It doesn't have to be particularly difficult to implement but I don't care for the moment. If any user is interested in the future, I could re-evaluate the issue.
